server:
  port: 8181

spring:
  application:
    name: resource-one
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security?createDatabaseIfNotExist=true
    username: root
    password: Abcde123@
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  main:
    allow-bean-definition-overriding=true:logging:
  level:
    org:
      hibernate:
        type: trace




zuul:
  routes:
    first-service:
      path: /ms1/**
      url: http://localhost:8081/

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8282/oauth/check_token
    client:
      client-id: mobile
      client-secret: abcde123

eureka:
  client:
    eureka-server-port: 8761
